openapi: 3.0.0
info:
  title: URL Shortener API
  description: A simple URL shortener API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /shorten:
    post:
      summary: Shorten a long URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                long_url:
                  type: string
                  description: The long URL to shorten
                  example: "https://www.example.com"
      responses:
        200:
          description: URL shortened successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    description: The shortened URL
                    example: "http://short.ly/abc123"
        400:
          description: Invalid URL format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Invalid URL format"
  /{short_url}:
    get:
      summary: Redirect to the long URL using the shortened URL
      parameters:
        - in: path
          name: short_url
          required: true
          description: The shortened URL
          schema:
            type: string
      responses:
        302:
          description: Redirects to the long URL
        404:
          description: URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "URL not found"
